### ISSUE TITLE
`godot` and `godot_console` aliases don't work as expected

### ISSUE THREAD

**Issue by Geometror** [adalinesimonian/gdvm#4]
### Linux
Running `godot` from the terminal just runs `gdvm` without the "run" parameter: 

![image](https://github.com/user-attachments/assets/c9055c79-1e97-4b35-a656-74d1c51de16c)

### Windows
While `godot`/`godot_console` works as expected when executed in a terminal, running via Powertoys Run (or just double-clicking the symlink in the .gdvm bin folder) doesn't open Godot, presumably because of the same issue described above (just `gdvm` without "run" is called).

Off-topic, but I just want to add: great project you've started here :)

**Comment by adalinesimonian** [comment]
Thanks for the issue report (and kind words 😊), fixed in v0.2.2. Looks like I won't be able to use symlinks, have to copy the binary.

Run `gdvm upgrade` and you should be good to go. You may _possibly_ need to run a non-`godot` gdvm command afterwards to let it replace the symlinks with copies. Running `gdvm --version` should work. Or, instead of running `upgrade` you could run the install command again from [the site](https://gdvm.io), that would work, too.
